global using Godot;
global using FileAccess = Godot.FileAccess;
global using LigerZero;
global using LigerZero.Common;
global using Tomlyn;
global using System.IO;
global using System.Text.Json.Serialization;
global using Env = System.Environment;
global using Engine = twodog.Engine;
global using CommandLine;
